execution:

- concurrency: 50

held for 3m

ramp up: 2m

scenario: Choose Flight

scenarios:

Choose Flight: requests:

-label: blazedeno

method: GET

url: http://blazedeno.com/

- label: reserve

method: POST

url: http://blazedemo.com/reserve.php

body fromPort: Paris

toPort: Buenos Aires
