name: Demo


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Run tests
      run: swift build -v
    - name: Run tests
      run: swift test -v
